Repository Team-jeong-ho-kim/Daedongyeojido_BE_v3, pull requests merged in 2024-12, with the labels that each got.

#1 setting
  build.gradle
  src/main/java/org/example/daedongyeojido_be/DaedongyeojidoBeApplication.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/domain/RefreshToken.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/exception/ExpiredTokenException.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/exception/InValidTokenException.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/exception/PasswordMismatchException.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/exception/UserAlreadyTaken.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/presentation/controller/AuthController.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/presentation/dto/request/LoginRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/presentation/dto/request/LogoutRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/presentation/dto/request/RefreshTokenRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/presentation/dto/request/RegisterRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/presentation/dto/response/LoginResponse.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/service/LoginService.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/service/LogoutService.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/service/RegisterService.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/service/ReissueService.java
  src/main/java/org/example/daedongyeojido_be/domain/user/domain/User.java
  src/main/java/org/example/daedongyeojido_be/domain/user/domain/enums/Role.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/InvalidUserException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/NotAuthenticatedException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/PasswordMismatchException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/UserMismatchException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/UserNotFoundException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/UsernameNotFoundException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/facade/UserFacade.java
  src/main/java/org/example/daedongyeojido_be/domain/user/presentation/controller/UserController.java
  src/main/java/org/example/daedongyeojido_be/domain/user/presentation/dto/Request/UpdateMyInfoRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/user/presentation/dto/Response/MyInfoResponse.java
  src/main/java/org/example/daedongyeojido_be/domain/user/repository/UserRepository.java
  src/main/java/org/example/daedongyeojido_be/domain/user/service/DeleteUserService.java
  src/main/java/org/example/daedongyeojido_be/domain/user/service/MyInfoService.java
  src/main/java/org/example/daedongyeojido_be/domain/user/service/UpdateMyInfoService.java
  src/main/java/org/example/daedongyeojido_be/global/config/SwaggerConfig.java
  src/main/java/org/example/daedongyeojido_be/global/config/config/FilterConfig.java
  src/main/java/org/example/daedongyeojido_be/global/config/config/RedisConfig.java
  src/main/java/org/example/daedongyeojido_be/global/config/config/SecurityConfig.java
  src/main/java/org/example/daedongyeojido_be/global/config/error/ErrorResponse.java
  src/main/java/org/example/daedongyeojido_be/global/config/error/GlobalExceptionFilter.java
  src/main/java/org/example/daedongyeojido_be/global/config/error/GlobalExceptionHandler.java
  src/main/java/org/example/daedongyeojido_be/global/config/error/exception/DayException.java
  src/main/java/org/example/daedongyeojido_be/global/config/error/exception/ErrorCode.java
  src/main/java/org/example/daedongyeojido_be/global/config/security/auth/AuthDetails.java
  src/main/java/org/example/daedongyeojido_be/global/config/security/auth/AuthDetailsService.java
  src/main/java/org/example/daedongyeojido_be/global/config/security/jwt/JwtProperties.java
  src/main/java/org/example/daedongyeojido_be/global/config/security/jwt/JwtTokenFilter.java
  src/main/java/org/example/daedongyeojido_be/global/config/security/jwt/JwtTokenProvider.java
  src/main/java/org/example/daedongyeojido_be/global/config/security/redis/RedisProperties.java
  src/main/resources/application.yml
Labels: ⚙️ setting

#2 main 프로젝트 세팅
  build.gradle
  src/main/java/org/example/daedongyeojido_be/DaedongyeojidoBeApplication.java
Labels: ⚙️ setting

#3 .
  src/main/java/org/example/daedongyeojido_be/domain/auth/presentation/dto/request/RegisterRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/service/RegisterService.java
Labels: 🧑‍💻 feat

#4 pr :: 이미지 업로드 서비스
  src/main/java/org/example/daedongyeojido_be/domain/auth/exception/ExpiredTokenException.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/exception/InValidTokenException.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/exception/PasswordMismatchException.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/exception/RefreshTokenNotFoundException.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/exception/UserAlreadyTaken.java
  src/main/java/org/example/daedongyeojido_be/domain/file/controller/FileController.java
  src/main/java/org/example/daedongyeojido_be/domain/file/controller/dto/FileResponse.java
  src/main/java/org/example/daedongyeojido_be/domain/file/domain/DefaultImageProperties.java
  src/main/java/org/example/daedongyeojido_be/domain/file/domain/type/ImageType.java
  src/main/java/org/example/daedongyeojido_be/domain/file/exception/FailFileException.java
  src/main/java/org/example/daedongyeojido_be/domain/file/service/FileDeleteService.java
  src/main/java/org/example/daedongyeojido_be/domain/file/service/FileUploadService.java
  src/main/java/org/example/daedongyeojido_be/domain/file/service/ImageService.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/InvalidUserException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/PasswordMismatchException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/UserMismatchException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/UserNotFoundException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/UsernameNotFoundException.java
  src/main/java/org/example/daedongyeojido_be/global/config/config/SecurityConfig.java
  src/main/java/org/example/daedongyeojido_be/global/config/error/GlobalExceptionFilter.java
  src/main/java/org/example/daedongyeojido_be/global/config/error/GlobalExceptionHandler.java
  src/main/java/org/example/daedongyeojido_be/global/config/error/exception/DaeDongException.java
  src/main/java/org/example/daedongyeojido_be/global/config/error/exception/ErrorCode.java
  src/main/java/org/example/daedongyeojido_be/infrastructure/s3/AwsS3Properties.java
  src/main/resources/application.yml
Labels: 🧑‍💻 feat

#5 🔀 :: User Api
  src/main/java/org/example/daedongyeojido_be/domain/club/presentation/dto/request/ModifyClubRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/user/domain/User.java
  src/main/java/org/example/daedongyeojido_be/domain/user/domain/enums/Role.java
  src/main/java/org/example/daedongyeojido_be/domain/user/exception/UnAuthorizeException.java
  src/main/java/org/example/daedongyeojido_be/domain/user/presentation/controller/UserController.java
  src/main/java/org/example/daedongyeojido_be/domain/user/presentation/dto/Request/UpdateMyInfoRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/user/presentation/dto/Response/MyInfoResponse.java
  src/main/java/org/example/daedongyeojido_be/domain/user/service/DeleteUserService.java
  src/main/java/org/example/daedongyeojido_be/domain/user/service/MyInfoService.java
Labels: 🧑‍💻 feat

#13 🔀 :: auth 관련 수정
  src/main/java/org/example/daedongyeojido_be/domain/auth/domain/RefreshToken.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/presentation/dto/request/LoginRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/auth/service/RegisterService.java
Labels: ♻️ refactor

#8 Like
  src/main/java/org/example/daedongyeojido_be/domain/feed/domain/Feed.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/domain/repository/FeedRepository.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/domain/repository/FeedRepositoryCustom.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/domain/repository/FeedRepositoryImpl.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/exception/CannotDeleteFeedException.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/exception/CannotModifyFeedException.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/exception/FeedNotFoundException.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/facade/FeedFacade.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/presentation/FeedController.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/presentation/dto/request/FeedRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/presentation/dto/response/FeedDetailResponse.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/presentation/dto/response/FeedListResponse.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/service/CreateFeedService.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/service/DeleteFeedService.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/service/QueryFeedDetailService.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/service/QueryMyAllFeedsService.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/service/UpdateFeedService.java
  src/main/java/org/example/daedongyeojido_be/domain/like/domain/Like.java
  src/main/java/org/example/daedongyeojido_be/domain/like/domain/repository/LikeRepository.java
  src/main/java/org/example/daedongyeojido_be/domain/like/exception/CannotDeleteLikeException.java
  src/main/java/org/example/daedongyeojido_be/domain/like/exception/LikeExistException.java
  src/main/java/org/example/daedongyeojido_be/domain/like/facade/LikeFacade.java
  src/main/java/org/example/daedongyeojido_be/domain/like/presentation/LikeController.java
  src/main/java/org/example/daedongyeojido_be/domain/like/service/DeleteLikeService.java
  src/main/java/org/example/daedongyeojido_be/domain/like/service/LikeService.java
  src/main/java/org/example/daedongyeojido_be/global/config/config/SecurityConfig.java
  src/main/java/org/example/daedongyeojido_be/global/config/error/exception/ErrorCode.java
Labels: 🧑‍💻 feat

#14 Auth, User
  src/main/java/org/example/daedongyeojido_be/domain/auth/service/RegisterService.java
  src/main/java/org/example/daedongyeojido_be/domain/user/domain/User.java
  src/main/java/org/example/daedongyeojido_be/global/config/security/jwt/JwtTokenFilter.java
Labels: ♻️ refactor

#15 🔀 :: club api
  src/main/java/org/example/daedongyeojido_be/domain/club/domain/Club.java
  src/main/java/org/example/daedongyeojido_be/domain/club/exception/ClubNotFoundException.java
  src/main/java/org/example/daedongyeojido_be/domain/club/presentation/controller/ClubController.java
  src/main/java/org/example/daedongyeojido_be/domain/club/presentation/dto/request/ModifyClubRequest.java
  src/main/java/org/example/daedongyeojido_be/domain/club/presentation/dto/response/AllClubResponse.java
  src/main/java/org/example/daedongyeojido_be/domain/club/presentation/dto/response/ClubInfoResponse.java
  src/main/java/org/example/daedongyeojido_be/domain/club/repository/ClubRepository.java
  src/main/java/org/example/daedongyeojido_be/domain/club/service/ClubAllInfoService.java
  src/main/java/org/example/daedongyeojido_be/domain/club/service/ClubInfoService.java
  src/main/java/org/example/daedongyeojido_be/domain/club/service/ClubModifyService.java
  src/main/resources/application.yml
  src/test/java/org/example/daedongyeojido_be/club/ClubAllInfoServiceTest.java
  src/test/java/org/example/daedongyeojido_be/club/ClubInfoServiceTest.java
  src/test/java/org/example/daedongyeojido_be/club/ClubModifyServiceTest.java
Labels: 🧑‍💻 feat

#17 Feed 유저부분 삭제
  src/main/java/org/example/daedongyeojido_be/domain/feed/domain/Feed.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/service/CreateFeedService.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/service/DeleteFeedService.java
  src/main/java/org/example/daedongyeojido_be/domain/feed/service/UpdateFeedService.java
Labels: ♻️ refactor
